/**
 * Database seed.
 *
 * Loads the default NDTECH branding profile (+ a couple of samples) and creates
 * a fully mock firmware so the UI/CLI can be exercised end-to-end without any
 * real (proprietary) Huawei firmware. The mock firmware is clearly flagged.
 */
import 'dotenv/config';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { prisma } from '../src/db.js';
import { config } from '../src/config.js';
import { DEFAULT_NDTECH_PROFILE } from '@ndtech/shared';
import * as firmwareService from '../src/services/firmwareService.js';
import * as analysisService from '../src/services/analysisService.js';
import * as workspaceService from '../src/services/workspaceService.js';

const SAMPLE_PROFILES = [
  DEFAULT_NDTECH_PROFILE,
  {
    ...DEFAULT_NDTECH_PROFILE,
    name: 'NDTECH Dark',
    primaryColor: '#0ea5e9',
    secondaryColor: '#22c55e',
    isDefault: false,
  },
  {
    ...DEFAULT_NDTECH_PROFILE,
    name: 'NDTECH NOC',
    productName: 'NDTECH NOC Gateway',
    primaryColor: '#6366f1',
    secondaryColor: '#f59e0b',
    isDefault: false,
  },
];

async function ensureStorageDirs(): Promise<void> {
  for (const dir of [config.uploadsDir, config.workspacesDir, config.exportsDir, config.profilesDir]) {
    await fs.mkdir(dir, { recursive: true });
  }
}

async function seedProfiles(): Promise<void> {
  for (const p of SAMPLE_PROFILES) {
    await prisma.brandingProfile.upsert({
      where: { name: p.name },
      update: {},
      create: {
        name: p.name,
        companyName: p.companyName,
        productName: p.productName,
        supportText: p.supportText,
        website: p.website,
        footerText: p.footerText,
        primaryColor: p.primaryColor,
        secondaryColor: p.secondaryColor,
        loginTitle: p.loginTitle,
        dashboardTitle: p.dashboardTitle,
        logoPath: p.logoPath,
        faviconPath: p.faviconPath,
        isDefault: p.isDefault ?? false,
      },
    });
  }
  console.log(`Seeded ${SAMPLE_PROFILES.length} branding profile(s).`);
}

/** Generate a small placeholder "firmware" file (NOT real Huawei firmware). */
async function writeMockFirmwareFile(): Promise<string> {
  const target = path.join(config.uploadsDir, 'mock-hg8145v5-v2-demo.bin');
  // ~64 KiB of filler with a couple of recognisable ASCII markers.
  const size = 64 * 1024;
  const buf = Buffer.alloc(size, 0);
  buf.write('NDTECH-MOCK-FIRMWARE uImage', 0, 'ascii');
  buf.write('hsqs', 0x4000, 'ascii'); // SquashFS magic marker for realism
  buf.write('Huawei EchoLife Home Gateway', 0x8000, 'ascii');
  await fs.writeFile(target, buf);
  return target;
}

async function seedMockFirmware(): Promise<void> {
  const existing = await prisma.firmware.findFirst({ where: { isMock: true } });
  if (existing) {
    console.log('Mock firmware already present; skipping pipeline seed.');
    return;
  }

  const storagePath = await writeMockFirmwareFile();
  const firmware = await firmwareService.registerFirmware({
    storagePath,
    originalName: 'mock-hg8145v5-v2-demo.bin',
    notes: 'Mock demo firmware generated by seed — NOT a real Huawei image.',
    isMock: true,
  });
  console.log(`Registered mock firmware ${firmware.id} (sha256 ${firmware.sha256.slice(0, 12)}…).`);

  const analysis = await analysisService.runAnalysis(firmware.id);
  console.log(`Analysis ${analysis.status} (${analysis.partitions.length} partitions, mock=${analysis.isMock}).`);

  const workspace = await workspaceService.createWorkspace(firmware.id);
  console.log(`Workspace ${workspace.status}; web-root candidates: ${workspace.webRootCandidates.length}.`);
}

async function main(): Promise<void> {
  console.log('NDTECH ONT Customizer — seeding database...');
  await ensureStorageDirs();
  await seedProfiles();
  await seedMockFirmware();
  console.log('Seed complete.');
}

main()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
